/** Canonical tool names for docs and regression tests. */
export const TOOL_CATALOG = [
  "apps_help",
  "apps_auth_status",
  "apps_clear_token_cache",
  "apps_get_customer",
  "apps_get_charge",
  "apps_get_paid_payment",
  "apps_get_installments_payment",
  "apps_list_advance_plans",
  "apps_get_advance_plan",
  "apps_create_advance_plan",
  "apps_update_advance_plan",
  "apps_delete_advance_plan",
  "apps_list_advance_plan_contractors",
  "apps_list_products",
  "apps_get_product",
  "apps_create_product",
  "apps_update_product",
  "apps_delete_product",
  "apps_list_product_purchasers",
  "apps_list_paid_plans",
  "apps_get_paid_plan",
  "apps_create_paid_plan",
  "apps_update_paid_plan",
  "apps_delete_paid_plan",
  "apps_list_paid_plan_subscribers",
  "apps_list_installment_plans",
  "apps_get_installment_plan",
  "apps_create_installment_plan",
  "apps_update_installment_plan",
  "apps_delete_installment_plan",
  "apps_list_installment_plan_subscribers",
  "apps_list_coupons",
  "apps_get_coupon",
  "apps_create_coupon",
  "apps_update_coupon",
  "apps_delete_coupon",
  "apps_get_discord_role",
  "apps_create_discord_role",
  "apps_update_discord_role",
  "apps_delete_discord_role",
  "apps_get_discord_channel",
  "apps_create_discord_channel",
  "apps_update_discord_channel",
  "apps_delete_discord_channel",
] as const;

export type ToolName = (typeof TOOL_CATALOG)[number];
